CREATE DATABASE Filmore
GO

USE Filmore
GO
CREATE TABLE Administrators
(
	Id  INT IDENTITY(1,1) NOT NULL,
	Firstname NVARCHAR(40) NOT NULL,
	Lastname NVARCHAR(40) NOT NULL,
	Password NVARCHAR(40) NOT NULL
	CONSTRAINT PK_Administrators PRIMARY KEY(Id)
	
)

GO
CREATE TABLE Clients
(
	Id INT IDENTITY(1,1) NOT NULL, 
	Firstname NVARCHAR(40) NOT NULL,
	Lastname NVARCHAR(40) NOT NULL,
	Password NVARCHAR(40) NOT NULL,
	EmailAddress NVARCHAR(40) NOT NULL,
	Address NVARCHAR(40) NOT NULL,
	ZipCode INT NOT NULL,
	City NVARCHAR(40) NOT NULL,
	Country NVARCHAR(40) NOT NULL,
	Blocked  BIT   NOT NULL   DEFAULT 0,	
	CONSTRAINT PK_Clients PRIMARY KEY(Id)

)
/* TYPE 1=FILM  2=SERIE*/
GO
CREATE TABLE Medias
(
	Id INT IDENTITY(1,1) NOT NULL, 
	Type TINYINT NOT NULL, 
	Name NVARCHAR(40) NOT NULL,
	Genre NVARCHAR(40) NOT NULL,
	Duree INT,
	NbSaison TINYINT,
	CONSTRAINT PK_Medias PRIMARY KEY(Id)

)

GO
CREATE TABLE Commandes
(
	Id INT IDENTITY(1,1) NOT NULL,
	Client_Id INT NOT NULL,
	Media_Id INT NOT NULL, 
	CONSTRAINT PK_Commandes PRIMARY KEY(Id),
	CONSTRAINT FK1_Commandes FOREIGN KEY(Client_Id) REFERENCES Clients(Id),
	CONSTRAINT FK2_Commandes FOREIGN KEY(Media_Id) REFERENCES Medias(Id)
)